version: '3'
services:
  icecast:
    image: "mcfiredrill/icecast:latest"
    ports:
      - "8000:8000"
    restart: "always"
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    command: "redis-server --requirepass ${REDIS_PASSWORD}"
  postgres:
    image: "postgres:9.4"
    ports:
      - 5432
    volumes:
      - postgres_data_9.4:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  rails:
    image: "streampusher/streampusher:latest"
    user: rails
    working_dir: /home/rails/app
    command: ./script/rails
    env_file: .env
    environment: &shared_env
      POSTGRESQL_HOST: postgres
      POSTGRESQL_PORT: 5432
      POSTGRESQL_USERNAME: postgres
      REDIS_HOST: redis
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/home/rails/app
      - /tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"
  sidekiq:
    image: "streampusher/streampusher:latest"
    user: root
    working_dir: /home/rails/app
    command: ./docker_wrapper.sh bundle exec sidekiq
    env_file: .env
    environment:
      <<: *shared_env
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/home/rails/app
      -  /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp

volumes:
  postgres_data_9.4:
